routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Route::group(['prefix' => 'admin'], function () {

	Auth::routes();
	
	Route::group(['middleware' => 'App\Http\Middleware\AdminMiddleware'], function() {
		Route::get('/', 'AdminController@index');
		Route::resource('noticias', 'NoticiasController');
		Route::resource('correlativities', 'CorrelativitiesController');
		Route::resource('examDates', 'ExamDatesController');
		Route::resource('schedules', 'SchedulesController');
		Route::resource('resumes', 'ResumesController');
	});

});

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Noticia.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Noticia extends Model
{
	protected $fillable = [
	'title', 'lead', 'description', 'link'
	];

    public static function boot() {
    	parent::boot();

    	static::deleting(function($model)
    	{
    		foreach ($model->image as $key => $image) {
    			$image->delete();
    		}
    	});
    }
    
	public function setLinkAttribute($value)
    {
        $this->attributes['link'] = str_replace(['http://', 'https://'], '' ,$value);
    }

	public function image() {
		return $this->morphMany('App\Models\Image', 'imageable');
	}
}

app/Http/Controllers/NoticiasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Noticia;
use App\Models\Image;
use View;
use Intervention\Image\ImageManagerStatic as IntImage;

class NoticiasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $noticias = Noticia::all();

        return View::make('admin.noticias.index', compact('noticias'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return View::make('admin.noticias.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'description' => 'required',
            'image' => 'max:8192',
            ]);

        $data = $request->all();

        $imagenDB = null;

        if ( !is_null($request->image) ) {
            $imagen = IntImage::make($request->image);
            $rutaGuardado = public_path().'/upload/img/';
            $filename = str_random(32);
            $imagen->save($rutaGuardado.$filename);
            
            $imagenDB = Image::firstOrNew(['filename' => $filename]);
        }
        
        $noticia = Noticia::create($data);

        if( !is_null($imagenDB) ) {
            $noticia->image()->save($imagenDB);
        }

        return redirect('admin/noticias')->withMessage('Noticia creada correctamente.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {

        Noticia::find($id)->delete();

        $responseOk = 'Noticia eliminada.';
        if ( $request->ajax() ) {
            return json_encode(['code' => 'ok', 'message' => $responseOk]);
        }

        return redirect()->back()->withMessage($responseOk);
    }
}

resources/views/admin/noticias/create.blade.php
@extends('layouts.admin')

@section('content')

<div class="row">
	<div class="col-sm-4 col-sm-offset-4">
		{{ Form::open(['url' => 'admin/noticias', 'files' => true]) }}
		
		<div class="form-group">
			{{ Form::label('position', 'Posición', ['class' => 'control-label']) }}
			{{ Form::select('position', selectRangeFirstValue(App\Models\Noticia::all()->count()+1, 'Seleccione una'), null, ['class' => 'form-control']) }}
		</div>

		<div class="form-group">
			{{ Form::label('title', 'Título', ['class' => 'control-label']) }}
			{{ Form::text('title', null, ['class' => 'form-control', 'maxlength' => 255]) }}
		</div>

		<div class="form-group">
			{{ Form::label('lead', 'Epígrafe', ['class' => 'control-label']) }}
			{{ Form::text('lead', null, ['class' => 'form-control']) }}
		</div>

		<div class="form-group">
			{{ Form::label('description', 'Cuerpo', ['class' => 'control-label']) }}
			{{ Form::textarea('description', null, ['class' => 'form-control']) }}
		</div>

		<div class="form-group">
			{{ Form::label('image', 'Imagen', ['class' => 'control-label']) }}
			{{ Form::file('image', null, ['class' => 'form-control']) }}
		</div>

		<div class="form-group">
			{{ Form::label('link', 'Link', ['class' => 'control-label']) }}
			{{ Form::text('link', null, ['class' => 'form-control']) }}
		</div>

		{{ Form::submit('Guardar', ['class' => 'btn btn-primary']) }}
	</div>
</div>
@endsection

resources/views/admin/noticias/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
	<div class="col-sm-4 col-sm-offset-4">
		{{ Form::model($noticia, ['url' => route('noticias.update', [$noticia->id]), 'files' => true, 'method' => 'patch']) }}

		<div class="form-group">
			{{ Form::label('name', 'Año', ['class' => 'control-label']) }}
			{{ Form::text('name', $noticia->name, ['class' => 'form-control', 'maxlength' => 255]) }}
		</div>

		<div class="form-group">
			{{ Form::label('position', 'Posición', ['class' => 'control-label']) }}
			{{ Form::selectRange('position', 1, App\Models\Noticia::all()->count(), $noticia->position, ['class' => 'form-control']) }}
		</div>

		{{ Form::submit('Guardar', ['class' => 'btn btn-primary']) }}
	</div>
</div>
@endsection

resources/views/admin/noticias/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
	<div class="col-md-12">
		<table class="table table-striped">
			<tr>
				<th>Título</th>
				<th>Epígrafe</th>
				<th>Cuerpo</th>
				<th>Acciones</th>
			</tr>	
			@forelse ($noticias as $noticia)
			<tr>
				<td>{{ str_limit($noticia->title,30) }}</td>
				<td>{{ str_limit($noticia->lead,150) }}</td>
				<td>{{ str_limit($noticia->description,150) }}</td>
				<td>
					{{ Form::open(['class' => 'delete', 'action' => ['NoticiasController@destroy',$noticia->id], 'method' => 'delete']) }}
					{{ Form::submit('Eliminar', ['class' => 'btn btn-danger btn-delete']) }}
					{{ Form::close() }}
				</td>
			</tr>		
			@empty
			<tr>
				<td>No hay actualmente noticias cargadas</td>
			</tr>
			@endforelse
		</table>
	</div>
	<div class="col-md-12 text-center">
		<a href="{{ action('NoticiasController@create') }}" class="btn btn-primary">Nueva noticia</a>
	</div>
</div>
@endsection

@section('scripts')
<script>
	$('.btn-delete').click(function(){
		confirm('¿Va a eliminar el elemento, está seguro?');
	})	

	$('.delete').submit(function(e){

		$.ajaxSetup({
			headers: {
				'X-CSRF-TOKEN': $('[name^="_token"]').val()
			}
		});

		form = $(this);
		action = form.attr('action');
		
		e.preventDefault();

		$.when($.ajax({
			url: action,
			type: 'delete',
		})).done(function(data){
			res = JSON.parse(data);

			iziToast.show({
				title: res.message,
				class: 'iziToast-color-green',
				timeout: 5000,
				icon: 'fa fa-check',
			});

			form.closest('tr').fadeOut(50);
		})

	});
</script>
@endsection