routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Route::group(['prefix' => 'admin'], function () {

	Auth::routes();
	
	Route::group(['middleware' => 'App\Http\Middleware\AdminMiddleware'], function() {
		Route::get('/', 'AdminController@index');
		Route::resource('noticias', 'NoticiasController');
		Route::resource('correlativities', 'CorrelativitiesController');
		Route::resource('examDates', 'ExamDatesController');
		Route::resource('schedules', 'SchedulesController');
		Route::resource('resumes', 'ResumesController');
	});

});

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Schedule.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Schedule extends Model
{
    protected $fillable = ['name', 'position'];
	

    public static function boot() {
    	parent::boot();

    	static::deleting(function($model)
    	{
    		foreach ($model->image as $key => $image) {
    			$image->delete();
    		}
    	});
    }
    
	public function image() {
		return $this->morphMany('App\Models\Image', 'imageable');
	}
}

app/Http/Controllers/SchedulesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Schedule;
use App\Models\Image;
use View;
use Intervention\Image\ImageManagerStatic as IntImage;

class SchedulesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $schedules = Schedule::orderBy('position')->get();

        return View::make('admin.schedules.index', compact('schedules'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return View::make('admin.schedules.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:schedules|max:255',
            'image' => 'required|max:8192',
            ]);

        $data = $request->all();
        
        $imagen = IntImage::make($request->image);
        $rutaGuardado = public_path().'/upload/img/';
        $filename = str_random(32);
        $imagen->save($rutaGuardado.$filename);

        $imagenDB = Image::firstOrNew(['filename' => $filename]);
        
        $schedule = Schedule::create($data);

        $schedule->image()->save($imagenDB);

        return redirect('admin/schedules')->withMessage('Horario de cursado creado correctamente.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $schedule = Schedule::find($id);

        return View::make('admin.schedules.edit', compact('schedule'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $schedule = Schedule::find($id);

        $schedule->fill($request->all());

        $schedule->save();

        return redirect('admin/schedules')->withMessage('Horario de cursado actualizado correctamente.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        Schedule::find($id)->delete();

        $responseOk = 'Horario de cursado eliminado.';
        if ( $request->ajax() ) {
            return json_encode(['code' => 'ok', 'message' => $responseOk]);
        }

        return redirect()->back()->withMessage($responseOk);
    }
}

resources/views/admin/schedules/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
	<div class="col-sm-4 col-sm-offset-4">
		{{ Form::open(['url' => 'admin/schedules', 'files' => true]) }}

		<div class="form-group">
			{{ Form::label('name', 'Año', ['class' => 'control-label']) }}
			{{ Form::text('name', null, ['class' => 'form-control', 'maxlength' => 255]) }}
		</div>

		<div class="form-group">
			{{ Form::label('image', 'Imagen', ['class' => 'control-label']) }}
			{{ Form::file('image', null, ['class' => 'form-control']) }}
		</div>

		<div class="form-group">
			{{ Form::label('position', 'Posición', ['class' => 'control-label']) }}
			{{ Form::select('position', selectRangeFirstValue(App\Models\Schedule::all()->count()+1, 'Seleccione una'), null, ['class' => 'form-control']) }}
		</div>

		{{ Form::submit('Guardar', ['class' => 'btn btn-primary']) }}
	</div>
</div>
@endsection

resources/views/admin/schedules/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
	<div class="col-sm-4 col-sm-offset-4">
		{{ Form::model($schedule, ['url' => route('schedules.update', [$schedule->id]), 'files' => true, 'method' => 'patch']) }}

		<div class="form-group">
			{{ Form::label('name', 'Año', ['class' => 'control-label']) }}
			{{ Form::text('name', $schedule->name, ['class' => 'form-control', 'maxlength' => 255]) }}
		</div>

		<div class="form-group">
			{{ Form::label('position', 'Posición', ['class' => 'control-label']) }}
			{{ Form::selectRange('position', 1, App\Models\Schedule::all()->count(), $schedule->position, ['class' => 'form-control']) }}
		</div>

		{{ Form::submit('Guardar', ['class' => 'btn btn-primary']) }}
	</div>
</div>
@endsection

resources/views/admin/schedules/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
	<div class="col-md-12">
		<table class="table table-striped">
			<tr>
				<th>Año</th>
				<th>Imagen</th>
				<th>Posición</th>
				<th>Acciones</th>
			</tr>	
			@forelse ($schedules as $schedule)
			<tr>
				<td>{{ $schedule->name }}</td>
				<td></td>
				<td width="10%">{{ $schedule->position }}</td>
				<td width="20%">
					<div class="row">
						<div class="col-md-6">
							<a href="{{ route('schedules.edit', [$schedule->id]) }}" class="btn btn-success">Editar</a>
						</div>
						<div class="col-md-6">
							{{ Form::open(['class' => 'delete', 'action' => ['SchedulesController@destroy',$schedule->id], 'method' => 'DELETE']) }}
							{{ Form::submit('Eliminar', ['class' => 'btn btn-danger btn-delete']) }}
							{{ Form::close() }}
						</div>
					</div>
				</td>
			</tr>
			@empty
			<tr>
				<td>No hay actualmente horarios de cursado cargados</td>
			</tr>
			@endforelse
		</table>
	</div>
	<div class="col-md-12 text-center">
		<a href="{{ action('SchedulesController@create') }}" class="btn btn-primary">Nuevo horario de cursado</a>
	</div>
</div>
@endsection

@section('scripts')
<script>
	$('.btn-delete').click(function(){
		confirm('¿Va a eliminar el elemento, está seguro?');
	})

	$('.delete').submit(function(e){

		$.ajaxSetup({
			headers: {
				'X-CSRF-TOKEN': $('[name^="_token"]').val()
			}
		});

		form = $(this);
		action = form.attr('action');
		
		e.preventDefault();

		$.when($.ajax({
			url: action,
			type: 'delete',
		})).done(function(data){
			res = JSON.parse(data);

			iziToast.show({
				title: res.message,
				class: 'iziToast-color-green',
				timeout: 5000,
				icon: 'fa fa-check',
			});

			form.closest('tr').fadeOut(50);
		})

	});
</script>
@endsection