routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Route::group(['prefix' => 'admin'], function () {

	Auth::routes();
	
	Route::group(['middleware' => 'App\Http\Middleware\AdminMiddleware'], function() {
		Route::get('/', 'AdminController@index');
		Route::resource('noticias', 'NoticiasController');
		Route::resource('correlativities', 'CorrelativitiesController');
		Route::resource('examDates', 'ExamDatesController');
		Route::resource('schedules', 'SchedulesController');
		Route::resource('resumes', 'ResumesController');
	});

});

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Correlativity.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Correlativity extends Model
{
    protected $fillable = ['name'];
	
    public static function boot() {
    	parent::boot();

    	static::deleting(function($model)
    	{
    		foreach ($model->image as $key => $image) {
    			$image->delete();
    		}
    	});
    }

	public function image() {
		return $this->morphMany('App\Models\Image', 'imageable');
	}
}

app/Http/Controllers/CorrelativitiesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Correlativity;
use App\Models\Image;
use View;
use Intervention\Image\ImageManagerStatic as IntImage;

class CorrelativitiesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $correlativities = Correlativity::all();

        return View::make('admin.correlativities.index', compact('correlativities'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return View::make('admin.correlativities.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:correlativities|max:255',
            'image' => 'required|max:8192',
            ]);

        $data = $request->all();
        
        $imagen = IntImage::make($request->image);
        $rutaGuardado = public_path().'/upload/img/';
        $filename = str_random(32);
        $imagen->save($rutaGuardado.$filename);

        $imagenDB = Image::firstOrNew(['filename' => $filename]);
        
        $correlativity = Correlativity::create($data);

        $correlativity->image()->save($imagenDB);

        return redirect('admin/correlativities')->withMessage('Correlatividad creada correctamente.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $correlativity = Correlativity::find($id);

        return View::make('admin.correlativities.edit', compact('correlativity'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $correlativity = Correlativity::find($id);

        $correlativity->fill($request->all());

        $correlativity->save();

        return redirect('admin/correlativities')->withMessage('Correlatividad actualizada correctamente.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        Correlativity::find($id)->delete();

        $responseOk = 'Correlatividad eliminada.';
        if ( $request->ajax() ) {
            return json_encode(['code' => 'ok', 'message' => $responseOk]);
        }

        return redirect()->back()->withMessage($responseOk);
    }
}

resources/views/admin/correlativities/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
	<div class="col-sm-4 col-sm-offset-4">
		{{ Form::open(['url' => 'admin/correlativities', 'files' => true]) }}

		<div class="form-group">
			{{ Form::label('name', 'Año', ['class' => 'control-label']) }}
			{{ Form::text('name', null, ['class' => 'form-control', 'maxlength' => 255]) }}
		</div>		

		<div class="form-group">
			{{ Form::label('image', 'Imagen', ['class' => 'control-label']) }}
			{{ Form::file('image', null, ['class' => 'form-control']) }}
		</div>

		{{ Form::submit('Guardar', ['class' => 'btn btn-primary']) }}
	</div>
</div>
@endsection

resources/views/admin/correlativities/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
	<div class="col-sm-4 col-sm-offset-4">
		{{ Form::model($correlativity, ['url' => route('correlativities.update', [$correlativity->id]), 'files' => true, 'method' => 'patch']) }}

		<div class="form-group">
			{{ Form::label('name', 'Año', ['class' => 'control-label']) }}
			{{ Form::text('name', $correlativity->name, ['class' => 'form-control', 'maxlength' => 255]) }}
		</div>

		<div class="form-group">
			{{ Form::label('position', 'Posición', ['class' => 'control-label']) }}
			{{ Form::selectRange('position', 1, App\Models\Correlativity::all()->count(), $correlativity->position, ['class' => 'form-control']) }}
		</div>

		{{ Form::submit('Guardar', ['class' => 'btn btn-primary']) }}
	</div>
</div>
@endsection

resources/views/admin/correlativities/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
	<div class="col-md-12">
		<table class="table table-striped">
			<tr>
				<th>Año</th>
				<th>Imagen</th>
				<th>Posición</th>
				<th>Acciones</th>
			</tr>	
			@forelse ($correlativities as $correlativity)
			<td>{{ $correlativity->name }}</td>
			<td></td>
			<td width="10%">{{ $correlativity->position }}</td>
			<td width="20%">
				<div class="row">
					<div class="col-md-6">
						<a href="{{ route('correlativities.edit', [$correlativity->id]) }}" class="btn btn-success">Editar</a>
					</div>
					<div class="col-md-6">
						{{ Form::open(['class' => 'delete', 'action' => ['CorrelativitiesController@destroy',$correlativity->id], 'method' => 'DELETE']) }}
						{{ Form::submit('Eliminar', ['class' => 'btn btn-danger btn-delete']) }}
						{{ Form::close() }}
					</div>
				</div>
			</td>		
			@empty
			<tr>
				<td>No hay actualmente correlatividades cargadas</td>
			</tr>
			@endforelse
		</table>
	</div>
	<div class="col-md-12 text-center">
		<a href="{{ action('CorrelativitiesController@create') }}" class="btn btn-primary">Nueva correlatividad</a>
	</div>
</div>
@endsection

@section('scripts')
<script>
	$('.btn-delete').click(function(){
		confirm('¿Va a eliminar el elemento, está seguro?');
	})

	$('.delete').submit(function(e){

		$.ajaxSetup({
			headers: {
				'X-CSRF-TOKEN': $('[name^="_token"]').val()
			}
		});

		form = $(this);
		action = form.attr('action');
		
		e.preventDefault();

		$.when($.ajax({
			url: action,
			type: 'delete',
		})).done(function(data){
			res = JSON.parse(data);

			iziToast.show({
				title: res.message,
				class: 'iziToast-color-green',
				timeout: 5000,
				icon: 'fa fa-check',
			});

			form.closest('tr').fadeOut(50);
		})

	});
</script>
@endsection